services:
  - type: web
    name: pdf-qa-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: BEARER_TOKEN
        sync: false
      - key: PINECONE_INDEX_NAME
        value: pdf-qa-index
      - key: PINECONE_CLOUD
        value: aws
      - key: PINECONE_REGION
        value: us-east-1